name: CI
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'scripts/**'
      - 'src/**'
      - 'test/**'
      - '**.cabal'
      - '**.nix'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'scripts/**'
      - 'src/**'
      - 'test/**'
      - '**.cabal'
      - '**.nix'
  workflow_dispatch:

jobs:
  hspec:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - id: extract_nixpkgs_url
        run:
          # `nix eval --raw --impure --expr '(import ./flake.nix).inputs.nixpkgs.url'` can detect the nixpkgs url, but it requires nix... I want this information before installing nix :<
          echo "url=$(ruby -e 'puts File.read("flake.nix").slice(/nixpkgs = { url = "([^"]+)/, 1)')" | tee -a $GITHUB_OUTPUT
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=${{ steps.extract_nixpkgs_url.outputs.url }}
      # https://github.com/cachix/install-nix-action/blob/5c11eae19dba042788936d4f1c9685fdd814ac49/README.md?plain=1#L80-L85
      # Actually don't work for specifying nix_path...
      - id: detect_nixpkgs
        name: Detect nixpkgs version
        run: echo "nixpkgs_version=$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | tr -d '"')" | tee -a $GITHUB_OUTPUT
      - uses: cachix/cachix-action@v12
        with:
          name: asdf2json
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # How to cache nix store is https://github.com/kachick/dotfiles/blob/b264b152302cf38afe46d513f5a4cd9531197958/.github/workflows/ci-dev.yml#L28-L32
      # No big benefit exists...
      - name: Print current versions
        run: |
          nix develop --command bash -c '
            which ghc
            ghc --version
            which cabal
            cabal --version
            which stack
            stack --version
            dprint --version
            '
      - name: Cache cabal global
        id: cache-cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-global-${{ hashFiles('**.nix', '**.cabal') }}
      - name: Cache cabal local
        id: cache-cabal-local
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-cabal-local-${{ hashFiles('**.nix', '**.cabal') }}
      - name: Cabal update
        if: steps.cache-cabal-global.outputs.cache-hit != 'true' || steps.cache-cabal-local.outputs.cache-hit != 'true'
        run: nix develop --command bash -c 'cabal update'
      - run: nix develop --command bash -c 'cabal test'
