name: CI
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'scripts/**'
      - 'src/**'
      - 'test/**'
      - '**.cabal'
      - '**.nix'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'scripts/**'
      - 'src/**'
      - 'test/**'
      - '**.cabal'
      - '**.nix'
  workflow_dispatch:

jobs:
  hspec:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - uses: cachix/cachix-action@v12
        with:
          name: asdf2json
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - run: cabal update
      - run: cabal test
