name: Release
on:
  push:
  workflow_dispatch:

jobs:
  release_linux:
    # https://github.com/softprops/action-gh-release/blob/d4e8205d7e959a9107da6396278b2f1f07af0f9b/README.md?plain=1#L216-L234
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/5a350a8f31bb7ef0c6e79aea3795a890cf7743d4.tar.gz
      - id: detect_nixpkgs
        name: Detect nixpkgs version
        run: echo "nixpkgs_version=$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | grep -Po '[^"]+')" | tee -a $GITHUB_OUTPUT
      - uses: cachix/cachix-action@v12
        with:
          name: asdf2json
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - name: Cache cabal global
        id: cache-cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-${{ steps.detect_nixpkgs.outputs.nixpkgs_version }}-cabal-global-${{ hashFiles('default.nix', '**.cabal') }}
      - name: Cache cabal local
        id: cache-cabal-local
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ steps.detect_nixpkgs.outputs.nixpkgs_version }}-cabal-local-${{ hashFiles('default.nix', '**.cabal') }}
      - name: Cabal update
        if: steps.cache-cabal-global.outputs.cache-hit != 'true' || steps.cache-cabal-local.outputs.cache-hit != 'true'
        run: cabal update
      - name: Build
        run: cabal v2-install --installdir=dist --install-method=copy --overwrite-policy=always
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/asdf2json
