name: Release
on:
  push:
  workflow_dispatch:

jobs:
  release_linux:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - uses: cachix/cachix-action@v12
        with:
          name: asdf2json
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
      - name: Cache cabal global
        id: cache-cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-global-${{ hashFiles('default.nix', '**.cabal') }}
      - name: Cache cabal local
        id: cache-cabal-local
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-cabal-local-${{ hashFiles('default.nix', '**.cabal') }}
      - name: Build
        run: cabal v2-install --installdir=dist --install-method=copy --overwrite-policy=always
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/asdf2json
