name: Release
on:
  push:
  workflow_dispatch:

jobs:
  release_linux:
    # https://github.com/softprops/action-gh-release/blob/d4e8205d7e959a9107da6396278b2f1f07af0f9b/README.md?plain=1#L216-L234
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - id: extract_nixpkgs_url
        run:
          # `nix eval --raw --impure --expr '(import ./flake.nix).inputs.nixpkgs.url'` can detect the nixpkgs url, but it requires nix... I want this information before installing nix :<
          echo "url=$(ruby -e 'puts File.read("flake.nix").slice(/nixpkgs = { url = "([^"]+)/, 1)')" | tee -a $GITHUB_OUTPUT
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=${{ steps.extract_nixpkgs_url.outputs.url }}
      - id: detect_nixpkgs
        name: Detect nixpkgs version
        run: echo "nixpkgs_version=$(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | tr -d '"')" | tee -a $GITHUB_OUTPUT
      - uses: cachix/cachix-action@v12
        with:
          name: asdf2json
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Print current versions
        run: |
          nix develop --command bash -c '
            which ghc
            ghc --version
            which cabal
            cabal --version
            which stack
            stack --version
            dprint --version
            '
      - name: Cache cabal global
        id: cache-cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-global-${{ hashFiles('**.nix', '**.cabal') }}
      - name: Cache cabal local
        id: cache-cabal-local
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-cabal-local-${{ hashFiles('**.nix', '**.cabal') }}
      - name: Cabal update
        if: steps.cache-cabal-global.outputs.cache-hit != 'true' || steps.cache-cabal-local.outputs.cache-hit != 'true'
        run: nix develop --command bash -c 'cabal update'
      - name: Build
        run: nix develop --command bash -c 'cabal v2-install --installdir=dist --install-method=copy --overwrite-policy=always'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/asdf2json
